function dateInPast() {
  var d = new Date()
  d.setDate(0)
  return d
}

function dateInFuture() {
  var d = new Date()
  d.setDate((d.getDate() + 20))
  return d
}


const campaigns = [
  {
    //Campaign metadata
    campaign_id: 'sdhgvisdgfh8249724fskdjgh',
    brand_id: '324729346798123245',
    //This type field could be used to auto populate various parts of the campaign
    campaign_type: 'simple_static_percentage',
    active: true,

    //Dates
    //The dates from and to which a campaign will be active
    start_date: dateInPast(),
    end_date: dateInFuture(),

    //Conditions
    //All must evaluate to true for a redemption to be triggered
    conditions: {
      time_conditions: {
        //The hours of the day in which this campaign will trigger a redemption. 
        //A null value means the campaign is redeemable at any time.
        time_of_day: null,
        //The day of the week in which this campaign will trigger a redemption.
        //A null value means the campaign is redeemable all week. 
        day_of_week: [1, 3, 4, 5]
      },
      purchase_conditions: {
        minimum_spend: 300
      }
    },

    //Value Constraints
    //A set of constraints which govern the value generated by this campaign
    value_constraints: {
      value_type: {
        dynamic: false
      },
      //A range between which a dynamic value would be calculated
      //Set to null when value_type.dynamic === false
      dynamic_value_range: null,
      //The static value generated by this camapaign
      //Set to null when value_type.dynamic === true
      static_value_amount: 0.05,
      //A min and max value constraining the actual cashback created by a static or dynamic value 
      cashback_range: {
        minimum_cashback: 1,
        maximum_cashback: 10000
      }
    },

    //Messaging
    //Customised messaging for use in app and push notifications
    messaging: {
      push_notification_message: "Thanks for coming bro!",
      app_snippet: "Redeem this!"
    },

    //Fineprint governing this campaign
    fineprint: {
      standard_fineprint: 'lorem ipsum',
      specific_fineprint: 'dates etc blah blah'
    }
  }
]

module.exports.Campaigns = campaigns;